name: Install Konveyor
description: |
  Install Konveyor Operator.
inputs: 
  bundle_image:
    description: "image url for operator bundle container image"
    required: false
    default: ""
  namespace:
    description: "the namespace where konveyor should be installed"
    required: false
    default: ""
  tackle_cr:
    description: "JSON encoded Tackle Custom Resource (CR) string"
    required: false
    default: ""
  disable_maven_search:
    description: "Disable maven central search"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
  - name: Install kubectl
    shell: bash
    run: |
      if command -v kubectl >/dev/null 2>&1; then
        echo "kubectl is already installed...yay"
        exit 0
      fi
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  - name: Install operator-sdk
    shell: bash
    run: |
      if command -v operator-sdk >/dev/null 2>&1; then
        echo "operator-sdk is already installed...yay"
        exit 0
      fi
      curl -LO https://github.com/operator-framework/operator-sdk/releases/download/v1.35.0/operator-sdk_linux_amd64
      sudo install -o root -g root -m 0755 operator-sdk_linux_amd64 /usr/local/bin/operator-sdk
  - name: Install Konveyor
    env:
      OPERATOR_BUNDLE_IMAGE: ${{ inputs.bundle_image }}
      NAMESPACE: ${{ inputs.namespace }}
      TACKLE_CR: ${{ inputs.tackle_cr }}
      DISABLE_MAVEN_SEARCH: ${{ inputs.disable_maven_search }}
    run: make install-konveyor
    working-directory: ${{ github.action_path }}/../../..
    shell: bash
  - name: Upload logs on fail
    if: ${{ failure() }}
    uses: actions/upload-artifact@v4
    with:
      name: debug-output
      path: /tmp/konveyor-debug
