name: Install tackle operator
description: |
  Install Tackle Operator.
inputs: 
  operator-bundle-image:
    description: "image url for operator bundle container image"
    required: false
    default: "quay.io/konveyor/tackle2-operator-bundle:latest"
  hub-image:
    description: "image url for tackle-hub"
    required: false
    default: "quay.io/konveyor/tackle2-hub:latest"
  ui-image:
    description: "image url for tackle-ui"
    required: false
    default: "quay.io/konveyor/tackle2-ui:latest"
  addon-analyzer-image:
    description: "image url for analyzer addon"
    required: false
    default: "quay.io/konveyor/tackle2-addon-analyzer:latest"
  image-pull-policy:
    description: "Image Pull Policy"
    required: false
    default: "Always"
  analyzer-container-cpu:
    description: "The CPU request value for the analyzer task containers"
    required: false
    default: 0
  analyzer-container-memory:
    description: "The memory request value for the analyzer task containers"
    required: false
    default: 0
  enable_auth:
    description: "Enable tackle with auth"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
  - name: Install kubectl
    shell: bash
    run: |
      if command -v kubectl >/dev/null 2>&1; then
        echo "kubectl is already installed...yay"
        exit 0
      fi
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  - name: Install operator-sdk
    shell: bash
    run: |
      if command -v operator-sdk >/dev/null 2>&1; then
        echo "operator-sdk is already installed...yay"
        exit 0
      fi
      curl -LO https://github.com/operator-framework/operator-sdk/releases/download/v1.35.0/operator-sdk_linux_amd64
      sudo install -o root -g root -m 0755 operator-sdk_linux_amd64 /usr/local/bin/operator-sdk
  - name: Install tackle
    run: |
      export OPERATOR_BUNDLE_IMAGE="${{ inputs.operator-bundle-image }}"
      export HUB_IMAGE="${{ inputs.hub-image }}"
      export UI_IMAGE="${{ inputs.ui-image }}"
      export ADDON_ANALYZER_IMAGE="${{ inputs.addon-analyzer-image }}"
      export IMAGE_PULL_POLICY="${{ inputs.image-pull-policy }}"
      export ANALYZER_CONTAINER_REQUESTS_MEMORY="${{ inputs.analyzer-container-memory }}"
      export ANALYZER_CONTAINER_REQUESTS_CPU="${{ inputs.analyzer-container-cpu }}"
      if [[ "true" == "${{ inputs.enable_auth }}"]]; then
        export FEATURE_AUTH_REQUIRED=true
      fi
      make install-tackle
    working-directory: ${{ github.action_path }}/../../..
    shell: bash
  - name: Upload logs on fail
    if: ${{ failure() }}
    uses: actions/upload-artifact@v4
    with:
      name: debug-output
      path: /tmp/konveyor-debug
