name: Install tackle operator
description: |
  Install Tackle Operator.
inputs: 
  tackle-operator-index-image:
    description: "image url for operator index"
    required: false
    default: "quay.io/konveyor/tackle2-operator-index:latest"
  tackle-hub-image:
    description: "image url for tackle-hub"
    required: false
    default: "quay.io/konveyor/tackle2-hub:latest"
  tackle-pathfinder-image:
    description: "image url for pathfinder image"
    required: false
    default: "quay.io/konveyor/tackle-pathfinder:1.3.0-native"
  tackle-ui-image:
    description: "image url for tackle-ui"
    required: false
    default: "quay.io/konveyor/tackle2-ui:latest"
  tackle-addon-admin-image:
    description: "image urd for admin addon"
    required: false
    default: "quay.io/konveyor/tackle2-addon:latest"
  tackle-addon-windup-image:
    description: "image url for windup addon"
    required: false
    default: "quay.io/konveyor/tackle2-addon-windup:latest"
  tackle-image-pull-policy:
    description: "Image Pull Policy"
    required: false
    default: "Always"
  tackle-windup-container-cpu:
    description: "The CPU request value for the windup task containers"
    required: false
    default: 0
  tackle-windup-container-memory:
    description: "The memory request value for the windup task containers"
    required: false
    default: 0
  # TODO(djzager): uncomment when supported
  # tackle-operator-container-image:
  #   description: "image url for operator container"
  #   required: false
  #   default: "quay.io/konveyor/tackle2-operator:latest"
runs:
  using: "composite"
  steps:
  # TODO(djzager): Need to figure out overriding operator image
  # or maybe just installing manager via kustomize.
  - name: Install tackle
    run: |
      export TACKLE_OPERATOR_INDEX_IMAGE="${{ inputs.tackle-operator-index-image }}"
      export TACKLE_HUB_IMAGE="${{ inputs.tackle-hub-image }}"
      export TACKLE_PATHFINDER_IMAGE="${{ inputs.tackle-pathfinder-image }}"
      export TACKLE_UI_IMAGE="${{ inputs.tackle-ui-image }}"
      export TACKLE_ADDON_ADMIN_IMAGE="${{ inputs.tackle-addon-admin-image }}"
      export TACKLE_ADDON_WINDUP_IMAGE="${{ inputs.tackle-addon-windup-image }}"
      export TACKLE_IMAGE_PULL_POLICY="${{ inputs.tackle-image-pull-policy }}"
      export TACKLE_WINDUP_CONTAINER_REQUESTS_MEMORY="${{ inputs.tackle-windup-container-memory }}"
      export TACKLE_WINDUP_CONTAINER_REQUESTS_CPU="${{ inputs.tackle-windup-container-cpu }}"
      make install-tackle
    working-directory: ${{ github.action_path }}/../../..
    shell: bash
