---
collections:
  - name: operator_sdk.util
    version: "0.5.0"
  - name: kubernetes.core
    version: "2.4.0"
  - name: cloud.common
    version: "2.1.1"
  - name: community.general
    version: "4.8.11"
  - name: community.postgresql
    version: "3.10.2"
