---
apiVersion: v1
kind: Namespace
metadata:
  name: konveyor-tackle
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: konveyor-tackle
  namespace: konveyor-tackle
spec:
  displayName: Tackle Operator
  publisher: Konveyor
  sourceType: grpc
  image: quay.io/konveyor/tackle2-operator-index:latest
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: konveyor-tackle
  namespace: konveyor-tackle
spec:
  targetNamespaces:
    - konveyor-tackle
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: tackle-operator
  namespace: konveyor-tackle
spec:
  channel: v2.0.0-beta
  installPlanApproval: Automatic
  name: tackle-operator
  source: konveyor-tackle
  sourceNamespace: konveyor-tackle
