---
- name: "Check for existing {{ idpclient.name }} IdpClient"
  k8s_info:
    api_version: tackle.konveyor.io/v1alpha1
    kind: IdpClient
    name: "{{ idpclient.name }}"
    namespace: "{{ app_namespace }}"
  register: existing_idpclient

- name: "Create/update {{ idpclient.name }} IdpClient if operator-managed"
  when: (existing_idpclient.resources | length) == 0 or (existing_idpclient.resources[0].metadata.labels['app.kubernetes.io/part-of'] | default('') == app_name)
  k8s:
    state: present
    definition: "{{ lookup('template', idpclient.template) }}"
