# All RBAC will be applied under this service account in
# the deployment namespace. You may comment out this resource
# if your manager will use a service account that exists at
# runtime. Be sure to update RoleBinding and ClusterRoleBinding
# subjects if changing service account names.
resources:
- hub_service_account.yaml
- hub_role.yaml
- hub_role_binding.yaml
- service_account.yaml
- ui_service_account.yaml
- ui_cluster_role.yaml
- ui_cluster_role_binding.yaml
- cluster_role.yaml
- cluster_role_binding.yaml
- role.yaml
- role_binding.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
