name: Start minikube
description: |
  Start minikube and prepare it for Tackle.
inputs:
  driver:
    description: 'Choose a specific driver, one of: docker, none, podman, virtualbox, parallels, vmwarefusion, hyperkit, vmware, ssh'
    required: false
    default: ''
  container-runtime:
    description: 'Choose a specific container-runtime, one of: docker, containerd, cri-o'
    required: false
    default: ''
  kubernetes-version:
    description: 'Choose a specific version of Kubernetes, "stable" for the latest stable build, or "latest" for the latest development build'
    required: false
    default: ''
  cpus:
    description: 'Number of CPUs allocated to Kubernetes. Use "max" to use the maximum number of CPUs.'
    required: false
    default: ''
  memory:
    description: 'Amount of RAM to allocate to Kubernetes (format: <number>[<unit>], where unit = b, k, m or g). Use "max" to use the maximum amount of memory.'
    required: false
    default: ''
  cni:
    description: 'CNI plug-in to use. Valid options: auto, bridge, calico, cilium, flannel, kindnet, or path to a CNI manifest'
    required: false
    default: 'auto'
runs:
  using: "composite"
  steps:
  - name: Setup minikube
    uses: medyagh/setup-minikube@master
    with:
      driver: ${{ inputs.driver }}
      container-runtime: ${{ inputs.container-runtime }}
      kubernetes-version: ${{ inputs.kubernetes-version }}
      cpus: ${{ inputs.cpus }}
      memory: 8000
      cni: ${{ inputs.cni }}
  # Don't pass minikube start ${ARGS} as they are handled in setup-minikube
  - name: Start minikube
    run: make start-minikube
    working-directory: ${{ github.action_path }}/../../..
    shell: bash
