---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tackle-hub-role
rules:
- apiGroups:
  - ""
  - tackle.konveyor.io
  - batch
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use