name: Make Operator Bundle
description: |
  Make an operator bundle. This does not save the image for you.
inputs: 
  operator_bundle:
    description: "image uri for operator bundle (ie. quay.io/<namespace>/<image-name>:<tag>)"
    required: true
  operator:
    description: "image uri for operator (ie. quay.io/<namespace>/<image-name>:<tag>)"
    required: false
    default: ""
  oauth_proxy:
    description: "image uri for oauth_proxy (ie. quay.io/<namespace>/<image-name>:<tag>)"
    required: false
    default: ""
  tackle_hub:
    description: "image uri for tackle-hub (ie. quay.io/<namespace>/<image-name>:<tag>)"
    required: false
    default: ""
  tackle_postgres:
    description: "image uri for tackle-postgres (ie. quay.io/<namespace>/<image-name>:<tag>)"
    required: false
    default: ""
  keycloak_sso:
    description: "image uri for keycloak_sso image (ie. quay.io/<namespace>/<image-name>:<tag>)"
    required: false
    default: ""
  keycloak_init:
    description: "image uri for keycloak_init image (ie. quay.io/<namespace>/<image-name>:<tag>)"
    required: false
    default: ""
  tackle_ui:
    description: "image uri for tackle-ui (ie. quay.io/<namespace>/<image-name>:<tag>)"
    required: false
    default: ""
  addon_admin:
    description: "image uri for admin addon (ie. quay.io/<namespace>/<image-name>:<tag>)"
    required: false
    default: ""
  addon_analyzer:
    description: "image uri for analyzer addon (ie. quay.io/<namespace>/<image-name>:<tag>)"
    required: false
    default: ""
  version:
    description: "operator version"
    required: false
    default: ""
  channels:
    description: "comma separated channel(s) this operator should be available on"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
  - name: Make bundle
    env:
      CHANNELS: ${{ inputs.channels }}
      BUNDLE_IMAGE: ${{ inputs.operator_bundle }}
      VERSION: ${{ inputs.version }}
    run: |
      [ -n "${VERSION}" ] && export VERSION="${VERSION:1}"
      OPTS=""
      [ -n "${{ inputs.operator }}" ] && OPTS+=" --set images.operator=${{ inputs.operator }}"
      [ -n "${{ inputs.oauth_proxy }}" ] && OPTS+=" --set images.oauth_proxy=${{ inputs.oauth_proxy }}"
      [ -n "${{ inputs.tackle_hub }}" ] && OPTS+=" --set images.tackle_hub=${{ inputs.tackle_hub }}"
      [ -n "${{ inputs.tackle_postgres }}" ] && OPTS+=" --set images.tackle_postgres=${{ inputs.tackle_postgres }}"
      [ -n "${{ inputs.keycloak_sso }}" ] && OPTS+=" --set images.keycloak_sso=${{ inputs.keycloak_sso }}"
      [ -n "${{ inputs.keycloak_init }}" ] && OPTS+=" --set images.keycloak_init=${{ inputs.keycloak_init }}"
      [ -n "${{ inputs.tackle_ui }}" ] && OPTS+=" --set images.tackle_ui=${{ inputs.tackle_ui }}"
      [ -n "${{ inputs.addon_admin }}" ] && OPTS+=" --set images.addon_admin=${{ inputs.addon_admin }}"
      [ -n "${{ inputs.addon_analyzer }}" ] && OPTS+=" --set images.addon_analyzer=${{ inputs.addon_analyzer }}"
      HELM_TEMPLATE_OPTS="${OPTS}" make bundle
      cat ./bundle/manifests/konveyor-operator.clusterserviceversion.yaml
      make bundle-build
    working-directory: ${{ github.action_path }}/../../..
    shell: bash
