name: Make Operator Bundle
description: |
  Make an operator bundle and save it. This does not save the image for you.
inputs: 
  operator_bundle:
    description: "image uri for operator bundle"
    required: true
  operator:
    description: "image uri for operator"
    required: false
    default: ""
  oauth_proxy:
    description: "image uri for oauth_proxy"
    required: false
    default: ""
  tackle_hub:
    description: "image uri for tackle-hub"
    required: false
    default: ""
  tackle_postgres:
    description: "image uri for tackle-postgres"
    required: false
    default: ""
  pathfinder:
    description: "image uri for pathfinder image"
    required: false
    default: ""
  keycloak_sso:
    description: "image uri for keycloak_sso image"
    required: false
    default: ""
  keycloak_init:
    description: "image uri for keycloak_init image"
    required: false
    default: ""
  tackle_ui:
    description: "image uri for tackle-ui"
    required: false
    default: ""
  addon_admin:
    description: "image uri for admin addon"
    required: false
    default: ""
  addon_analyzer:
    description: "image uri for analyzer addon"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
  # TODO(djzager): Need to figure out overriding operator image
  # or maybe just installing manager via kustomize.
  - name: Make bundle
    run: |
      OPTS=""
      [ -n "${{ inputs.operator }}" ] && OPTS+=" --set images.operator=${{ inputs.operator }}"
      [ -n "${{ inputs.oauth_proxy }}" ] && OPTS+=" --set images.oauth_proxy=${{ inputs.oauth_proxy }}"
      [ -n "${{ inputs.tackle_hub }}" ] && OPTS+=" --set images.tackle_hub=${{ inputs.tackle_hub }}"
      [ -n "${{ inputs.tackle_postgres }}" ] && OPTS+=" --set images.tackle_postgres=${{ inputs.tackle_postgres }}"
      [ -n "${{ inputs.pathfinder }}" ] && OPTS+=" --set images.pathfinder=${{ inputs.pathfinder }}"
      [ -n "${{ inputs.keycloack_sso }}" ] && OPTS+=" --set images.keycloack_sso=${{ inputs.keycloack_sso }}"
      [ -n "${{ inputs.keycloack_init }}" ] && OPTS+=" --set images.keycloack_init=${{ inputs.keycloack_init }}"
      [ -n "${{ inputs.tackle_ui }}" ] && OPTS+=" --set images.tackle_ui=${{ inputs.tackle_ui }}"
      [ -n "${{ inputs.addon_admin }}" ] && OPTS+=" --set images.addon_admin=${{ inputs.addon_admin }}"
      [ -n "${{ inputs.addon_analyzer }}" ] && OPTS+=" --set images.addon_analyzer=${{ inputs.addon_analyzer }}"
      HELM_TEMPLATE_OPTS="${OPTS}" make bundle
      git diff ./bundle
      BUNDLE_IMG="${{ inputs.operator_bundle }}" make bundle-build
    working-directory: ${{ github.action_path }}/../../..
    shell: bash
