version: "99.0.0"

# true in the case we want to render manifests for OLM stuff
olm: false
csv:
  replaces: ""
#   replaces: konveyor-operator.v0.3.0-beta.1.1
  skips: []
#   skips:
#     - konveyor-operator.v0.3.0-beta.1
#     - konveyor-operator.v0.3.0-beta.1.1

images:
  operator: quay.io/konveyor/tackle2-operator:release-0.9
  oauth_proxy: quay.io/openshift/origin-oauth-proxy:release-0.9
  tackle_hub: quay.io/konveyor/tackle2-hub:release-0.9
  tackle_postgres: quay.io/sclorg/postgresql-15-c9s:release-0.9
  keycloak_sso: quay.io/keycloak/keycloak:26.1
  tackle_ui: quay.io/konveyor/tackle2-ui:release-0.9
  addon_analyzer: quay.io/konveyor/tackle2-addon-analyzer:release-0.9
  addon_platform: quay.io/konveyor/tackle2-addon-platform:release-0.9
  addon_discovery: quay.io/konveyor/tackle2-addon-discovery:release-0.9
  provider_generic: quay.io/konveyor/generic-external-provider:release-0.9
  provider_java: quay.io/konveyor/java-external-provider:release-0.9
  provider_c_sharp: quay.io/konveyor/c-sharp-provider:release-0.9
  kantra: quay.io/konveyor/kantra:release-0.9
  kai: quay.io/konveyor/kai-solution-server:release-0.9
  lightspeed_stack: quay.io/lightspeed-core/lightspeed-stack:release-0.9
